# Form implementation generated from reading ui file 'negar_gui/uwin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_uwWindow(object):
    def setupUi(self, uwWindow):
        uwWindow.setObjectName("uwWindow")
        uwWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=uwWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.untouch_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.untouch_label.setObjectName("untouch_label")
        self.gridLayout_2.addWidget(self.untouch_label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.untouch_word = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.untouch_word.setObjectName("untouch_word")
        self.gridLayout.addWidget(self.untouch_word, 0, 0, 1, 1)
        self.untouch_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.untouch_button.setEnabled(False)
        self.untouch_button.setObjectName("untouch_button")
        self.gridLayout.addWidget(self.untouch_button, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.untouch_table = QtWidgets.QTableView(parent=self.centralwidget)
        self.untouch_table.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.untouch_table.setObjectName("untouch_table")
        self.gridLayout_3.addWidget(self.untouch_table, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        uwWindow.setCentralWidget(self.centralwidget)
        self.untouch_label.setBuddy(self.untouch_word)

        self.retranslateUi(uwWindow)
        QtCore.QMetaObject.connectSlotsByName(uwWindow)

    def retranslateUi(self, uwWindow):
        _translate = QtCore.QCoreApplication.translate
        uwWindow.setWindowTitle(_translate("uwWindow", "Immutable Words"))
        self.untouch_label.setText(_translate("uwWindow", "Add a &word to immutable words\' list:"))
        self.untouch_button.setText(_translate("uwWindow", "&Add"))
        self.untouch_button.setShortcut(_translate("uwWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    uwWindow = QtWidgets.QMainWindow()
    ui = Ui_uwWindow()
    ui.setupUi(uwWindow)
    uwWindow.show()
    sys.exit(app.exec())
