name: Deploy Python Executable file for Linux

on:
  release:
    types: [released]

env:
  APP_NAME: 'negar-gui'
  PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

# Declare default permissions as write-all.
permissions: write-all

jobs:
  linux-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install wheel Pillow PyQt6 pyperclip pyuca qrcode Image redlines requests regex docopt pyqtdarktheme toml
        pip install python-negar negar-gui
        pip install PyInstaller

    - name: 'Clone Python-negar repository'
      shell: bash
      run: |
        git clone https://github.com/shahinism/python-negar.git

    - name: 'Use PyInstaller tool to get executable output'
      shell: bash
      run: ./.github/build.sh

    - name: 'Make script executable'
      run: chmod +x ./dist/negar-gui*

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: Built
        path: dist/

    - name: 'Automatic release'
      uses: "softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77" # v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          dist/*
