name: Deploy Python Executable file for Linux

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  APP_NAME: 'negar-gui'
  PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

# Declare default permissions as write-all.
permissions: write-all

jobs:
  linux-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install wheel Pillow PyQt6 pyperclip pyuca qrcode Image redlines requests regex docopt pyqtdarktheme toml
        pip install python-negar negar-gui
        pip install PyInstaller

    - name: 'Clone Python-negar repository'
      shell: bash
      run: |
        git clone https://github.com/shahinism/python-negar.git

    - name: 'Use PyInstaller tool to get executable output'
      shell: bash
      run: ./.github/build.sh

    - name: 'Make script executable'
      run: chmod +x ./dist/negar-gui*

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Built
        path: dist/

    - name: 'Automatic release'
      uses: "softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228" # v3.0.2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          dist/*
