name: Deploy Python Executable file for Windows

on:
  push:
    branches:
    - "Production"
  release:
    types: [released]

env:
  APP_NAME: 'negar-gui'
  PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

# Declare default permissions as write-all.
permissions: write-all

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install wheel Pillow PyQt5 pyperclip pyuca qrcode Image requests python-negar negar-gui
        pip install PyInstaller

    - name: 'Clone Python-negar repository'
      shell: powershell
      run: |
        git clone https://github.com/shahinism/python-negar.git

    - name: 'Use PyInstaller tool to get executable output'
      shell: powershell
      run: ./.github/build.ps1

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: Built
        path: dist/

    - name: 'Automatic release'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.2.17-test"
        prerelease: false
        title: "Release Build"
        files: |
          dist/*.exe
